import pygame
from sys import exit
from os.path import join

CELL_SIZE = 80
ROWS = 10
COLUMNS = 16

WINDOW_WIDTH = COLUMNS * CELL_SIZE
WINDOW_HEIGHT = ROWS * CELL_SIZE

LIGHT_GREEN = "#aad751"
DARK_GREEN = "#a2d149"

START_LENGTH = 3
START_ROW = ROWS // 2
START_COLUMN = START_LENGTH + 2

SHADOW_SIZE = pygame.Vector2(4, 4)
SHADOW_OPACITY = 50